#### steps
Split the Data: Divide your data into training and testing sets.
Create a Model: Set up a Decision Tree model with specific rules.
Train the Model: Teach the model using the training data.
Make Predictions: Use the model to predict answers for the test data.
Evaluate the Model: Check how well the model did by comparing its predictions to the actual answers.


In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/scoliann/KnnEnsemble/refs/heads/master/datasets/balanceScale/balance-scale.data')
df.head()

,B,1,1.1,1.2,1.3
0,R,1,1,1,2
1,R,1,1,1,3
2,R,1,1,1,4
3,R,1,1,1,5
4,R,1,1,2,1


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624 entries, 0 to 623
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   B       624 non-null    object
 1   1       624 non-null    int64 
 2   1.1     624 non-null    int64 
 3   1.2     624 non-null    int64 
 4   1.3     624 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 24.5+ KB


In machine learning, we typically separate our data into features (also called independent variables or predictors) and target (also called dependent variable or label).  
  
  
Features (X): These are the input variables that the model uses to make predictions. They are the characteristics or attributes of the data.  
  
  
Target (y): This is the output variable that the model tries to predict.
  
  
By dropping 'Class Name', you are saying that 'Class Name' is your target variable, and you want to use all other columns as features to predict it.  
   
  
`X = df.drop('B', axis=1):` Creates a DataFrame X with all columns except 'Class Name'. These are your features.  
  
  
`y = df[['B']]:` Creates a DataFrame y with only the 'Class Name' column. This is your target variable.  
  
-> Together, these lines of code separate your dataset into features (X) and target (y), which is a common first step in preparing data for machine learning models.  
  

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
X= df.drop('B',axis=1)#to train
y=df[['B']]#to predict

In [9]:
from sklearn.metrics import confusion_matrix, classification_report

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize the Decision Tree Classifier
clf_model = DecisionTreeClassifier(criterion='gini', max_depth=3, min_samples_leaf=5, random_state=42)

# Train the model using the training data
clf_model.fit(X_train, y_train)

# Make predictions on the test set
#Uses the trained model to make predictions on the test data (X_test).
#The predictions are stored in y_pred.


y_pred = clf_model.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[ 0  7  5]
 [ 0 60 27]
 [ 0 15 74]]

Classification Report:
              precision    recall  f1-score   support

           B       0.00      0.00      0.00        12
           L       0.73      0.69      0.71        87
           R       0.70      0.83      0.76        89

    accuracy                           0.71       188
   macro avg       0.48      0.51      0.49       188
weighted avg       0.67      0.71      0.69       188



c:\Users\imane\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\imane\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\imane\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave

`confusion matrix, `shows how many predictions were correct and how many were wrong.  
y_test: The actual answers from the test data.  
y_pred: The predictions made by the model.  
`classification report, `which gives more detailed metrics about the model's performance.  
Includes precision, recall, f1-score, and support for each class.  



In [18]:
from sklearn.tree import export_text
target = list(set(df['B']))
features_names = list(X.columns)

`X.columns:` Accesses the column names of the DataFrame X.
`list(X.columns):` Converts these column names into a list.  
  
`export_text `is a function that converts a trained   decision tree model into a human-readable text format. This allows you to see the rules and logic that the decision tree uses to make predictions.

In [20]:
from sklearn.tree import export_text
r = export_text(clf_model, feature_names = features_names)
print(r)

|--- 1 <= 2.50
|   |--- 1.3 <= 2.50
|   |   |--- 1.2 <= 2.50
|   |   |   |--- class: L
|   |   |--- 1.2 >  2.50
|   |   |   |--- class: R
|   |--- 1.3 >  2.50
|   |   |--- 1.2 <= 1.50
|   |   |   |--- class: R
|   |   |--- 1.2 >  1.50
|   |   |   |--- class: R
|--- 1 >  2.50
|   |--- 1.1 <= 2.50
|   |   |--- 1.2 <= 1.50
|   |   |   |--- class: L
|   |   |--- 1.2 >  1.50
|   |   |   |--- class: R
|   |--- 1.1 >  2.50
|   |   |--- 1.3 <= 3.50
|   |   |   |--- class: L
|   |   |--- 1.3 >  3.50
|   |   |   |--- class: L




## Summary of Decision Tree Code Components

- **`export_text`**: Converts a decision tree model into a readable text format.

- **`feature_names`**: A list of feature names used to label the features in the text output.

- **`target`**: A list of unique class labels in your target variable.

- **`features_names = list(X.columns)`**: Creates a list of feature names from the DataFrame `X`.

- **`r = export_text(clf_model, feature_names=features_names)`**: Converts the decision tree model into text format using the feature names.

- **`print(r)`**: Prints the decision tree rules in a readable format.

These components of the code help you understand and visualize how your decision tree model makes predictions based on the input features.